### ISSUE TITLE
US 01.04.01 (Part 4) View My Books

### ISSUE THREAD

**Issue by JamiePowers4446** [cmput301w19t22/BookNet#28]
As an owner, I want to view a list of all my books, and their descriptions, statuses, and current borrowers, so that I can quickly get an overview of the books in my library, their status, and to whom they are borrowed.
Completed by Project Part 4
SP: 3

**Comment by Madoshakalaka** [comment]
I'm on this, currently, detailed book info is not showing when the user clicked on a booklisting.
