### ISSUE TITLE
US 01.05.01 (Part 5) View My Books Filtered By Status

### ISSUE THREAD

**Issue by JamiePowers4446** [cmput301w19t22/BookNet#29]
As an owner, I want to view a list of all my books, filtered by status, so that I can easily see which of my books have a certain status. Completed by Project Part 5
SP: 2

**Comment by Madoshakalaka** [comment]
I'm on this

**Comment by Madoshakalaka** [comment]
done.

worth noting: the update of owned books are in real time, which means when debugging/testing, changes from firebase console/ other users will directly change on your app.

To test this function, create some random books, go to firebase console, manually change some status to others (Borrowed, Requested etc). App will get immediate update.
