### ISSUE TITLE
US 02.03.01 (Part 4) Show User Profile

### ISSUE THREAD

**Issue by JamiePowers4446** [cmput301w19t22/BookNet#34]
As an owner or borrower, I want to retrieve and show the profile of a presented username, so that I can know more about a lender or borrower (e.g. to contact them).
Completed by Project Part 4
SP: 4

**Comment by JamiePowers4446** [comment]
UI for this is made, but it needs to read a user from db.

**Comment by Madoshakalaka** [comment]
I'll do this
