### ISSUE TITLE
US 04.02.01 (Part 5) View Books I Requested

### ISSUE THREAD

**Issue by JamiePowers4446** [cmput301w19t22/BookNet#38]
As a borrower, I want to view a list of books I have requested, each book with its description, and owner username, so that I can keep track of which books I have borrowed, and from whom.
Completed by Project Part 5
SP: 4

**Comment by JamiePowers4446** [comment]
UI is made for this.

**Comment by JamiePowers4446** [comment]
Only database interaction still needed.

**Comment by Madoshakalaka** [comment]
I'll do it

**Comment by Madoshakalaka** [comment]
done
