### ISSUE TITLE
US 04.03.01 (Part 4) Notify When My Book Is Requested

### ISSUE THREAD

**Issue by JamiePowers4446** [cmput301w19t22/BookNet#39]
As an owner, I want to be notified of a request, so that I know when someone is interested in borrowing my book.
Completed by Project Part 4
SP: 3

**Comment by wheredoesthisoceango** [comment]
Complete in notification tab.

**Comment by JamiePowers4446** [comment]
Needs to be implemented with push notifications as well.

**Comment by wheredoesthisoceango** [comment]
Complete
