### ISSUE TITLE
US 06.03.01 (Part 4) View Books I Am Borrowing

### ISSUE THREAD

**Issue by JamiePowers4446** [cmput301w19t22/BookNet#47]
As a borrower, I want to view a list of books I am borrowing, each book with its description and owner username, so that I can keep track of which books I have borrowed, and to whom I would have to return it.
Completed by Project Part 4
SP: 3

**Comment by wheredoesthisoceango** [comment]
Complete in the MyBooks tab, set spinner to borrowed.
